services:
  - type: web
    name: battleship
    runtime: node
    plan: free
    buildCommand: npm run install:all && npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        value: file:./dev.db
      - key: NODE_ENV
        value: production
